In [1]:
!pip install ipython-sql > out
!pip install psycopg2 > out

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
%load_ext sql

# Creating Tunnel to server

* user: erich
* pass: ?????
* port: 2122
* ip: 128.130.204.35

enter container with:

docker exec -it [container-id] bash


ssh -L 5432:localhost:5432 -p 2122 erich@128.130.204.35 -N

In [3]:
%sql postgresql://postgres:C09c1JNcpS7nSJ4@localhost:5432/ncanalyzer?client_encoding=utf8

'Connected: postgres@ncanalyzer'

In [4]:
%sql select table_name from information_schema.tables where table_schema = 'public' and table_type='BASE TABLE' limit 20

20 rows affected.

[('vin',),
 ('chainmerklebranch',),
 ('entity',),
 ('auxpow_vout',),
 ('vout_addresses',),
 ('transaction',),
 ('merklebranch',),
 ('auxpow_vin',),
 ('block',),
 ('vout',),
 ('metainfos',),
 ('address',),
 ('auxpow',),
 ('auxpow_vout_addresses',),
 ('squatting_analysis',),
 ('coinbase_addresses',),
 ('auxcoinbase_addresses',),
 ('nmcentity',),
 ('auxpow_address',),
 ('tmp_cluster_bitcoin',)]

Tables interesting for indicators:
* block
* transaction
* vin
* vout

.... i need a damn metadata part

we are looking at transactions as our entity - they are in the table transaction ( roughly 4 million lines) and reference the block

In [12]:
%sql select * from transaction limit 20

20 rows affected.

[('2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('d0833ab8d0b11490c596fe556dabf1f1f80aee8781aa7983d831c6741ce34cd4', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('026525e1f6c39739274b3271b25d813556ad4228dd1faaa00759ca5c6df334a5', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('60aca7e51dd7735c9b1254a5b28f560446716cabd0174e51d1d892cf5ecc1f31', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('7d89d5ab793ae633d4c5a74f34242af22f73e8fdfe29c4602e2d61089ef80273', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('0ce7cf745ca4a5d5e8b5d19158a9f83a0715a167a6787f12fe1c793f5c86355c', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('7ed38df4104af712de75005f1cbcfecea61345483efc5b7cb3ee23f422579073', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('77383cd3997c500e7b13a05a441e23a5d184deb27e41bf7e231ae1297c8f704a', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('ef6d8c22d5133407c4bf6bd7b6496318583e980ed65cd4f0f720ef0a77205363', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('188859c5d0e33849f3262d4d507eb1d65e1c123acc238365bac5012b3a15f321', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('1b104cca106faad3d9407e6d60f77ea7d2cd898440b37f02590af1e925e6a31b', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('6d66b90c970305fd677ca43205f0ccbf34e715fecff57c8bfd7e775380dce4cf', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('c8932ffebd7c7eecafa08c51aa1080af1e7a8815baca0d18ae340d83b53428c8', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('d93f73bebe695a03a5c8e327bb3118c7bb507bb942795da0d9efc2e84568dab3', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('5403e5d78137aa0c13c69ec5830c6eb1b52d43f2d83e15d06ae7042b10e98024', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('0d63d64612bbb6a11e272124370dcff0a457efbfa7b8868e37a89b913c2fa727', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('6b0316110339c0a6607fe3112d96a8c6e40755f3ce3c108cbf1794b51af03b2c', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('3cb72b84b833500206ff2d4ccee80c4ec378d21df37c0250cdef401644783ba2', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('20528d9e0b123d736df9cef8aaa26aa9c0568b32b791c7652441d8fbbcd620fc', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('5e5e4ea1b9d0b46be7a3a53c74a5dd0e4d592f2ee3633805c55faf8b428f5d84', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None)]

In [43]:
%sql DROP TABLE tmp_cluster_bitcoin 
%sql CREATE TABLE tmp_cluster_bitcoin AS SELECT txid, bitcoin_block_hash,time,blockheight,version FROM transaction

Done.
4223118 rows affected.

[]

In [41]:
#update the values of in 
%sql UPDATE vin as source SET value = upd.value FROM \
    vout as upd where not source.vin_txid isnull and source.vin_txid = upd.txid and source.referenced_vout = upd.n

8533266 rows affected.

[]

In [46]:
%sql select value isnull,count(1) from vin group by value isnull limit 20

2 rows affected.

[(False, 8533266), (True, 316754)]

# Indicators

*  regarding inputs:
    * #of inputs
    * transfered value in (sum of all input values)
    * largest_input
    * smallest_input
* regarding outputs:
    * #of outputs
    * transfered value out (sum of all output values)
    * largest_output
    * smallest_output
* misc
    * #of transactions in my block
    * script_type
    * time - transaction time

In [45]:
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN anz_inputs int
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN sum_in float
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN max_in float
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN min_in float


%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN anz_outputs int
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN sum_out float
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN max_out float
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN min_out float

%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN anz_trans_in_block int
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN script_type varchar

Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.
Done.

[]

In [47]:
%sql select * from tmp_cluster_bitcoin limit 10

10 rows affected.

[('2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('d0833ab8d0b11490c596fe556dabf1f1f80aee8781aa7983d831c6741ce34cd4', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('026525e1f6c39739274b3271b25d813556ad4228dd1faaa00759ca5c6df334a5', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('60aca7e51dd7735c9b1254a5b28f560446716cabd0174e51d1d892cf5ecc1f31', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('7d89d5ab793ae633d4c5a74f34242af22f73e8fdfe29c4602e2d61089ef80273', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('0ce7cf745ca4a5d5e8b5d19158a9f83a0715a167a6787f12fe1c793f5c86355c', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('7ed38df4104af712de75005f1cbcfecea61345483efc5b7cb3ee23f422579073', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('77383cd3997c500e7b13a05a441e23a5d184deb27e41bf7e231ae1297c8f704a', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('ef6d8c22d5133407c4bf6bd7b6496318583e980ed65cd4f0f720ef0a77205363', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None),
 ('188859c5d0e33849f3262d4d507eb1d65e1c123acc238365bac5012b3a15f321', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 1470144826, 28928, None, None, None, None, None, None, None, None, None, None)]

In [50]:
%sql UPDATE tmp_cluster_bitcoin as source SET anz_inputs = upd.anz_inputs , \
    sum_in = upd.sumv \
    ,max_in = upd.maxv \
    ,min_in = upd.minv \
    FROM \
( \
    SELECT trans.txid,count(1) as anz_inputs, sum(vin.value) as sumv, min(vin.value) as minv, max(vin.value) as maxv \
 from transaction as trans JOIN vin as vin \
    on trans.txid=vin.txid group by trans.txid \
) as upd where source.txid=upd.txid

4223118 rows affected.

[]

In [51]:
%sql UPDATE tmp_cluster_bitcoin as source SET anz_outputs = upd.anz_outputs , \
    sum_out = upd.sumv \
    ,max_out = upd.maxv \
    ,min_out = upd.minv \
    FROM \
( \
    SELECT trans.txid,count(1) as anz_outputs, sum(vout.value) as sumv, min(vout.value) as minv, max(vout.value) as maxv \
 from transaction as trans JOIN vout as vout \
    on trans.txid=vout.txid group by trans.txid \
) as upd where source.txid=upd.txid

4223118 rows affected.

[]

In [52]:
#add random number for sample generation
%sql ALTER TABLE tmp_cluster_bitcoin ADD COLUMN sample_id int
%sql UPDATE tmp_cluster_bitcoin as source SET sample_id = round(random() * 9 + 1)

Done.
4223118 rows affected.

[]

In [53]:
%sql select * from tmp_cluster_bitcoin limit 10

10 rows affected.

[('0274a71d63a38fcba31634473329df6e95ffa28543a22ccb291c35e944202e16', '8a7693d523191d06a6937a807249d80189a292733f09a6c624f3c861a837bdba', 1363091492, 1, 1, None, None, None, 1, 50.0, 50.0, 50.0, None, None, 9),
 ('84056589096902392298621b6073ff22e5e5c2d050018b64e5efa38d2751d745', '672d59a48e251807a31a873099960c5578ff3135f1cf4b887ae3cea3741d2ac5', 1372270809, 1, 1, None, None, None, 1, 50.3, 50.3, 50.3, None, None, 7),
 ('03ac0f6dca38a07667130a6e84cfebf19a6f7cf8463ac48668dcd8f5ce281298', 'fb04233fa5a172d8d32c06937078c10c06a52de5a531545686c2e7be001b296f', 1420422276, 1, 1, None, None, None, 1, 25.05, 25.05, 25.05, None, None, 10),
 ('03c05af95505e1b12692fce6594bed4ef3af43da20624fc9522067df39cd93d7', '4a2a41306d9527b0e7480b3596929af0bbb831bcdaf1235331f334ce0d45b512', 1367767129, 1, 1, None, None, None, 1, 50.44, 50.44, 50.44, None, None, 7),
 ('04625ecbe86c50cae530f899669f91b627b9b654a35aa70fb6995b3c0290df33', 'eefb6752a425f5c39c92e264b3edca1c591267ce08fbe1d80db2606c4f6d28aa', 1440254796, 1, 1, None, None, None, 1, 25.0, 25.0, 25.0, None, None, 7),
 ('04d4a5403eb9785e949025a9819c745fd7b5ba4eb85b8c7846002932ace94a37', '0000000000033cf38b3e536a4546c4ec37a08bb2401f056ae3fb3bd3d5107225', 1306680709, 1, 1, None, None, None, 1, 50.0, 50.0, 50.0, None, None, 9),
 ('0510b659351cbc9375d682d4edb193f618141e4193e4dbd971dd0353cef509ee', '44f59e53cd5b13128a263e683b0bcb2234c4f31545e398932eff88bf7dcd413b', 1368029260, 1, 1, None, None, None, 1, 50.01, 50.01, 50.01, None, None, 4),
 ('0580dc1494a8fb9183f6781b23c8212ee7b61e55d7b1b9566ecf7a4560bc4532', 'd3f8607633971d7ba8d659ca397338b37719d249001bc4ca2330d0cc07a4aebf', 1455602459, 1, 1, None, None, None, 1, 25.0, 25.0, 25.0, None, None, 2),
 ('05b97e02a1566b2160779250a9f4773fbf9cacafd30dc7755a3b69c1b7d59816', '6f68ad506cf911ea73938d906297b0e04b14817fa963de3f87208b87a43aee0b', 1363051027, 1, 1, None, None, None, 1, 50.01, 50.01, 50.01, None, None, 1),
 ('06577505a44e1065965de78b7be778b261bfd9229ba39410470e52adb819ecce', 'c5d6dae28b5101e79f9196974d09877252e6f48b0112e87640e380719be462ab', 1419391134, 1, 1, None, None, None, 1, 25.05, 25.05, 25.05, None, None, 8)]

* #of transactions in my block
* script_type

In [54]:
%sql UPDATE tmp_cluster_bitcoin as source SET anz_trans_in_block = upd.anz \
    FROM ( select bitcoin_block_hash, count(1)  as anz \
    FROM tmp_cluster_bitcoin group by bitcoin_block_hash ) as upd \
    where upd.bitcoin_block_hash = source.bitcoin_block_hash

4223118 rows affected.

[]

In [55]:
#script_type
%sql UPDATE tmp_cluster_bitcoin as source SET script_type = upd.script_type \
    FROM (  \
         SELECT txid,CASE WHEN count(distinct(type))>1 THEN 'mehr' ELSE max(type) END as script_type \
         FROM vout group by txid \
         ) as upd \
    where upd.txid = source.txid

4223118 rows affected.

[]

In [59]:
%sql select * from tmp_cluster_bitcoin where not min_in isnull limit 10

10 rows affected.

[('00004a87da3d45bb4927277d40902a22ea8c3a87c172b810d238efe68924683e', '410f664e829f93098bf10fc041a58134d7b24af14867cab96d86ca23008e0d44', 1426511293, 28928, 2, 25.36, 25.35, 0.01, 2, 25.36, 25.35, 0.01, 1036, 'mehr', 9),
 ('000067aab52e2fc6bbf6acf49369f5e7e5caf43e88ab9264db7c900783113431', '8efe9c7fa8114641c04f64a8c5266b0070ee253e395d76b12c267ac4602c95b6', 1426729457, 28928, 2, 22.9, 22.89, 0.01, 2, 22.89, 22.88, 0.01, 221, 'mehr', 8),
 ('00006a088a7d69602bc3dbb7f37ab89bd830806d3aa04f77b8401ecaa159c100', 'b5f8270000c0eaf2f20ea899caf4c248a9765e1d8e6769fa4cf502bfd5358ed2', 1470465833, 28928, 6, 25.95, 8.64, 0.01, 6, 25.92, 8.63, 0.01, 1419, 'mehr', 8),
 ('000086de5b8126754cb18509e574b3ef7626365cc4fc6d17597bca4b4c4d299d', '756c52f84827bd26f44164ac1db6918805fef4601aba3628fdb52ae6b33bbf14', 1431774960, 28928, 1, 48.46, 48.46, 48.46, 2, 48.46, 48.45, 0.01, 348, 'mehr', 6),
 ('0000e5b7217ee5f13bd808b1484abc1d43222364b09608c39bfabd14d55d6ad2', 'a8aa181b737360ff9e89cbb28bf9b46862b4392d39a749ed6bf5882a1a58154e', 1472222325, 28928, 2, 38.91, 38.9, 0.01, 2, 38.9, 38.89, 0.01, 26, 'mehr', 8),
 ('000118625d0ab13490b0317986d014172571642926bc9f30dc61250c340c9ff8', '5efcb37a709cb736f881d031305bfdcf33e8caa1e862ae2c29cc35f91e988578', 1446741931, 28928, 2, 13.18, 13.17, 0.01, 2, 13.17, 13.16, 0.01, 326, 'mehr', 7),
 ('000176f4c18b578088ee265b6004b2d434edd2f21372c2700bc2d51534d4b7d7', '51c8a30fe2dcfd5395e806ea2f4ae0559237a6f007d36fa6d4ba6ed9a4bde9cb', 1410052295, 28928, 1, 0.01, 0.01, 0.01, 1, 0.01, 0.01, 0.01, 28, 'pubkeyhash', 8),
 ('0001b50a5b744bcc23385e65f931f89f9c0f6c6042742a183022dc6a4f38b7fe', '285f032b26971de702446bb35b271ee05d43d574587e1c5d92a935e0bfadd100', 1448873436, 28928, 2, 18.39, 18.38, 0.01, 2, 18.39, 18.38, 0.01, 848, 'mehr', 8),
 ('00031eddc0f0f3fdaa49b61bf1ba4d5917ef2777e6a8300ffacc80b52fd44bce', 'abd8e7c7cb64684c5b5e55707497f3c56de812641f23f201fe8bb0a512a23bd6', 1468392895, 28928, 2, 10.02, 10.01, 0.01, 2, 10.01, 10.0, 0.01, 1115, 'mehr', 8),
 ('0003ca2c741607850eceec9a0181b6420fb1a4b21c19ef90ff10612a5bb32537', '1427970b0783f4ad5a80cedbabaf9a01e5aad578f87ce5edc8d04e8c95bf12a6', 1387564088, 1, 66, 9.23, 8.58, 0.01, 2, 9.31, 9.3, 0.01, 3, 'pubkeyhash', 6)]

In [65]:
%sql select sample_id ,count(1) from tmp_cluster_bitcoin group by sample_id

10 rows affected.

[(6, 469643),
 (8, 469817),
 (1, 234130),
 (2, 467688),
 (3, 470183),
 (10, 234457),
 (4, 468999),
 (5, 469046),
 (9, 470137),
 (7, 469018)]

In [67]:
import pandas as pd
result = %sql SELECT * FROM tmp_cluster_bitcoin where sample_id = 8
df = result.DataFrame()

469817 rows affected.

In [68]:
df.head()

,txid,bitcoin_block_hash,time,version,anz_inputs,sum_in,max_in,min_in,anz_outputs,sum_out,max_out,min_out,anz_trans_in_block,script_type,sample_id
0,000067aab52e2fc6bbf6acf49369f5e7e5caf43e88ab92...,8efe9c7fa8114641c04f64a8c5266b0070ee253e395d76...,1426729457,28928,2,22.90,22.89,0.01,2,22.89,22.88,0.01,221,mehr,8
1,00006a088a7d69602bc3dbb7f37ab89bd830806d3aa04f...,b5f8270000c0eaf2f20ea899caf4c248a9765e1d8e6769...,1470465833,28928,6,25.95,8.64,0.01,6,25.92,8.63,0.01,1419,mehr,8
2,0000e5b7217ee5f13bd808b1484abc1d43222364b09608...,a8aa181b737360ff9e89cbb28bf9b46862b4392d39a749...,1472222325,28928,2,38.91,38.90,0.01,2,38.90,38.89,0.01,26,mehr,8
3,000176f4c18b578088ee265b6004b2d434edd2f21372c2...,51c8a30fe2dcfd5395e806ea2f4ae0559237a6f007d36f...,1410052295,28928,1,0.01,0.01,0.01,1,0.01,0.01,0.01,28,pubkeyhash,8
4,0001b50a5b744bcc23385e65f931f89f9c0f6c6042742a...,285f032b26971de702446bb35b271ee05d43d574587e1c...,1448873436,28928,2,18.39,18.38,0.01,2,18.39,18.38,0.01,848,mehr,8

In [69]:
df.to_csv('namecoin_ml.csv',index=False)

# Testing


multiple inputs for each transaction are possible - see this one

In [14]:
%sql select * from vin where txid = '2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2'

2 rows affected.

[(8379517, None, None, None, 1, 4294967295, None, '87c34745827bda37dbeb92dd45f342225f4d3278ba9e4c27275edb00200ea4df', '2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2', None, None),
 (8379518, None, None, None, 0, 4294967295, None, 'cee866969baf5d9f22aac2252804734ed4cc26e90c9a116592a7a4d891def184', '2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2', None, None)]

value should be filled, but isnt - the transaction is referenced in vin_txid -> we have to look at the output of this transaction

In [18]:
%sql select * from vout where txid = '87c34745827bda37dbeb92dd45f342225f4d3278ba9e4c27275edb00200ea4df'

2 rows affected.

[(13415922, '0438e58eba34fd61972e5aee4f110c16de4cb4146eda8880e749823b25123f688f65afe2806ecf2553f218fc873a05da2e102cfd223c67fcac593a38c5cbfe521c OP_CHECKSIG', '410438e58eba34fd61972e5aee4f110c16de4cb4146eda8880e749823b25123f688f65afe2806ecf2553f218fc873a05da2e102cfd223c67fcac593a38c5cbfe521cac', 0, None, None, None, None, None, 1, 'pubkey', Decimal('14.33'), '87c34745827bda37dbeb92dd45f342225f4d3278ba9e4c27275edb00200ea4df', None, None),
 (13415923, 'OP_NAME_UPDATE 642f656c65646f6973696e 4269746d65737361676520616464726573733a20424d2d3263585434505a476f626871486d58566541597a506433426a4451456a6e33376a55 OP_2DROP OP_DROP OP_DUP OP_HASH160 008415b7e7883b927d7ae895a913be6b4e54f7a5 OP_EQUALVERIFY OP_CHECKSIG', '530b642f656c65646f6973696e394269746d65737361676520616464726573733a20424d2d3263585434505a476f626871486d58566541597a506433426a4451456a6e33376a556d7576a914008415b7e7883b927d7ae895a913be6b4e54f7a588ac', 1, None, 'd/eledoisin', 'name_update', None, 'Bitmessage address: BM-2cXT4PZGobhqHmXVeAYzPd3BjDQEjn37jU', 1, 'pubkeyhash', Decimal('0.01'), '87c34745827bda37dbeb92dd45f342225f4d3278ba9e4c27275edb00200ea4df', None, None)]

Script type is defined in : 
vout -> type

In [10]:
%sql select * from transaction limit  20

20 rows affected.

[('2d9fa35b88120b11e87557968351bfbdc87d9b238b6b3be1361945d3660a7cf2', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('d0833ab8d0b11490c596fe556dabf1f1f80aee8781aa7983d831c6741ce34cd4', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('026525e1f6c39739274b3271b25d813556ad4228dd1faaa00759ca5c6df334a5', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('60aca7e51dd7735c9b1254a5b28f560446716cabd0174e51d1d892cf5ecc1f31', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('7d89d5ab793ae633d4c5a74f34242af22f73e8fdfe29c4602e2d61089ef80273', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('0ce7cf745ca4a5d5e8b5d19158a9f83a0715a167a6787f12fe1c793f5c86355c', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('7ed38df4104af712de75005f1cbcfecea61345483efc5b7cb3ee23f422579073', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('77383cd3997c500e7b13a05a441e23a5d184deb27e41bf7e231ae1297c8f704a', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('ef6d8c22d5133407c4bf6bd7b6496318583e980ed65cd4f0f720ef0a77205363', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('188859c5d0e33849f3262d4d507eb1d65e1c123acc238365bac5012b3a15f321', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('1b104cca106faad3d9407e6d60f77ea7d2cd898440b37f02590af1e925e6a31b', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('6d66b90c970305fd677ca43205f0ccbf34e715fecff57c8bfd7e775380dce4cf', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('c8932ffebd7c7eecafa08c51aa1080af1e7a8815baca0d18ae340d83b53428c8', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('d93f73bebe695a03a5c8e327bb3118c7bb507bb942795da0d9efc2e84568dab3', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('5403e5d78137aa0c13c69ec5830c6eb1b52d43f2d83e15d06ae7042b10e98024', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('0d63d64612bbb6a11e272124370dcff0a457efbfa7b8868e37a89b913c2fa727', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('6b0316110339c0a6607fe3112d96a8c6e40755f3ce3c108cbf1794b51af03b2c', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('3cb72b84b833500206ff2d4ccee80c4ec378d21df37c0250cdef401644783ba2', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('20528d9e0b123d736df9cef8aaa26aa9c0568b32b791c7652441d8fbbcd620fc', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None),
 ('5e5e4ea1b9d0b46be7a3a53c74a5dd0e4d592f2ee3633805c55faf8b428f5d84', '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', 298311, 1470144826, 377, None, 0, True, 1470144826, 28928, '90b01d432fada37bceaa67041668cecb94018d1733bb64b57204d2ee0236c187', None)]